multitenancy:
  datasource-cache:
    maximumSize: 100
    expireAfterAccess: 1
  master:
    repository:
      packages: com.example.multitenancydemo.multitenancy.repositories
    entityManager:
      packages: com.example.multitenancydemo.multitenancy.entity
    datasource:
      url: jdbc:postgresql://localhost:5432/public
      username: postgres
      password: admin
    liquibase:
      changeLog: classpath:db/changelog/db.changelog-master.yaml
  tenant:
    repository:
      packages: com.example.multitenancydemo.repository
    entityManager:
      packages: com.example.multitenancydemo.entity
    datasource:
      url-prefix: jdbc:postgresql://localhost:5432/
      hikari:
        maximumPoolSize: 2
        minimumIdle: 0
        idleTimeout: 30000
    liquibase:
      changeLog: classpath:db/changelog/db.changelog-tenant.yaml



encryption:
  secret: test
  salt: test
